#!/usr/bin/env bash
rclone sync --progress --filter-from ~/enseeiht/.rclonefilter --max-size=1G ~/enseeiht/ penrose:enseeiht --log-file $HOME/enseeiht/.rclonelatest.log

set wd=$(pwd)
cd ~/enseeiht
git add .
git commit -m "backup at $(echo date --iso-8601)"
git push 
cd $wd
