(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter i: Z.

Parameter r: Z.

Axiom H : (0%Z < i)%Z.

Parameter r1: Z.

Axiom H1 : (r1 = (r + 1%Z)%Z).

Parameter i1: Z.

Axiom H2 : (i1 = (i - 1%Z)%Z).

(* Why3 goal *)
Theorem VC_somme : False.
Proof.


Qed.

