#!/bin/bash
echo 1 > /proc/sys/net/ipv4/ip_forward

ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 192.168.143.129/26 dev eth0
ip addr add 200.204.22.2/26 dev eth1

ip route add default via 200.204.22.1
ip route add 192.168.143.128/26 via 200.204.22.1
