#!/bin/bash
echo 1 > /proc/sys/net/ipv4/ip_forward
ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 200.204.22.193/26 dev eth0
ip addr add 200.204.22.131/26 dev eth1

ip route add default via 200.204.22.129
